### ISSUE TITLE
Was the mail notification feature purged?

### ISSUE THREAD

**Issue by dadosch** [robbi5/kleineanfragen#117]
I subscribed to get notifications by mail whenever a new Anfrage is added which matches a search. However, I cannot find this feature on the web page anymore?

**Comment by robbi5** [comment]
It's still there. For the parliaments of the states at the bottom of the page, for example: https://kleineanfragen.de/niedersachsen 
For new search matches at the bottom of the search result page: https://kleineanfragen.de/search?q=wasser

To get _all_ new documents, search for `*` - this was never an official feature :)

**Comment by dadosch** [comment]
Very sorry for the distraction -- uBlock origin blocked the button because of Fanboy’s Annoyance List. :confused:

**Comment by robbi5** [comment]
no problem, but thanks for the report. we have to change the html/css for those buttons then :)
