### ISSUE TITLE
mv 6/4640 ministry name is 'Ausschuss für ...'

### ISSUE THREAD

**Issue by globalworming** [robbi5/kleineanfragen#41]
we don't have a rule for that. Fix with nomenklatura? The PDF says "Ministerieum für..." so this may just be treated as duplicate. Or shall I treat Ausschuss as different entry?

**Comment by robbi5** [comment]
If the PDF says "Ministry for ..." it looks like someone from the Parlamentsdokumentation mis-clicked the answerer. 
Two possible solutions:
* we ignore "Ausschuss für..." and extract the correct ministry from the PDF text
* we rewrite "Ausschuss für ..." to "Ministerium für ..."

**Comment by globalworming** [comment]
extract name from pdf in https://github.com/robbi5/kleineanfragen/pull/67
