### ISSUE TITLE
SH is creative with hyphens

### ISSUE THREAD

**Issue by globalworming** [robbi5/kleineanfragen#43]
Text in the PDF uses different hypens, the app/extractors/schleswig_holstein_pdf_extractor.rb currently only covers one kind
– vs -

special hyphen is used in https://kleineanfragen.de/schleswig-holstein/18/3072-neuer-haushaltstitel-04-02-00-883-01-zuschuesse-fuer-die-sanierung-kommunaler-sportstaetten-unter-beruecksichtigung.txt

**Comment by robbi5** [comment]
We could use `\p{Pd}` or `\p{Dash_Punctuation}` there?
